= AsciiDoc

== Tables

I still find it confusing to work so here's a TL;DR of tables.

.Basic Table from Markdown
....
[cols="1,2", options="header", frame="all"] <.>
|===
| HEADER  | 2nd HEADER 
| 1       | stuffs 1 
| 2       | stuffs 2
| 3       | stuffs 3
| 4       | stuffs 4
| 5       | stuffs 5
| 6       | stuffs 6
| 7       | stuffs 7
| 8       | stuffs 8
| 9       | stuffs 9
| 10      | stuffs 10
|===
....
<.> The ``cols`` is probably the length.

If I want to have more columns, just add more items to columns.
``1,1,1,1`` would be 4 columns.

This should render as.

[cols="1,2", options="header", frame="all"]
|===
| HEADER  | 2nd HEADER 
| 1       | stuffs 1 
| 2       | stuffs 2
| 3       | stuffs 3
| 4       | stuffs 4
| 5       | stuffs 5
| 6       | stuffs 6
| 7       | stuffs 7
| 8       | stuffs 8
| 9       | stuffs 9
| 10      | stuffs 10
|===

== Code Block

.Python
....
[source, python] <.>
----
def main():
  print('test')
----
....
<.> You can remove ``source,`` and leave just the language, it still works.

That will render it below.

[source, python]
----
def main():
  print('test')
----

== Comparisons between +++****+++, ----, ====, and ....

This uses +++****+++
****
test
****

.This uses +++----+++
----
test
----

.This uses +++====+++
====
test
====

.This uses +++....+++
....
test
....

== Admonitions


----
NOTE: This command can be used as ... <.>
----
<.> Refer to https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions[AsciiDoc Documentation]. 

This should render as.

NOTE: This command can be used as ...

For multiple lines, use this

----
[NOTE]
====
Some text here

ANd here
====
----

[NOTE]
====
Some text here

ANd here
====

Types of admonitions:

* NOTE
* TIP
* IMPORTANT
* CAUTION
* WARNING


== Linking files for direct downloads

AsciiDoc's documentation for this can be found https://docs.antora.org/antora/latest/page/resource-id-coordinates/#id-resource[here].

Simply use ``attachment$`` https://docs.antora.org/antora/latest/page/resource-id-coordinates/#id-family[family coordinate].

.Direct Downloads
----
📒 repository <.>
  📄 antora.yml
  📂 modules
    📂 HackTheBox
      📂 pages
        📄 index.adoc
        📄 photon_lockdown.adoc
    📂random
      📂 attachments <.>
        📂 cmsc134-machine-problem-1
          📄 vuln.c <.>
      📂 pages
        📄 cmsc134-machine-problem-1.adoc
        📄 cmsc134-machine-problem-1-sources.adoc
        📄 cmsc134-machine-problem-1-writeup.adoc
        📄 cmsc134-machine-problem-2.adoc
        📄 cmsc134-writeups.adoc
        📄 index.adoc
    📂ROOT
      📄 nav.adoc
      📂 pages
        📄 example.adoc
        📄 index.adoc
    📂Root-Me
      📂 pages
        📄 ftp_authentication.adoc
        📄 index.adoc
        📄 telnet_authentication.adoc
        📄 twitter_authentication.adoc
----
<.> xref:writeups:ROOT:index.adoc[Writeups] (as of 2024/05/11)
<.> Add an ``attachments`` directory inside the module
<.> Target attachment file

Then link it with ``xref`` macro

....
xref:writeups:random:attachment$cmsc134-writeups/machine-problem-1/vuln.c[vuln.c]
....

It should look like this now.

xref:writeups:random:attachment$cmsc134-writeups/machine-problem-1/vuln.c[vuln.c]

This will ask you to download the file.

It is also possible to use text files as includes.

....
[,c]
----
\include::writeups:random:attachment$cmsc134-writeups/machine-problem-1/vuln.c[]
----
....


[,c]
----
include::writeups:random:attachment$cmsc134-writeups/machine-problem-1/vuln.c[]
----

Visit xref:writeups:random:cmsc134-writeups/machine-problem-1/sources.adoc[this] working reference.
