= 知識
:page-aliases: root, home, 知識

I no longer use https://obsidian.md[Obsidian] for taking notes.
Everything will be stored here including other stuffs that I do.
I didn't like my setup in https://github.com/KrulYuno/obsidian_files[Obsidian Notes] and was annoying to keep track of the files.

This xref:setup.adoc[setup] feels much easier to track although it has a few features that I miss from Obsidian (like backlinks, wikilinks, and graphs).

[NOTE]
As of June 6, 2024, I won't be tranferring my https://github.com/KrulYuno/obsidian_files[Obsidian Notes] here.
I noticed that I dislike taking notes.
A lot.
So, my golden rule for now is to write notes *that matters* to me.
Writing notes what I read through class or from courses just drains me from actually learning and reading.

Hence, I'll stop taking notes that doesn't matter much.

[IMPORTANT]
If you want to learn better, make sure to do the following:

. Predict
. Simulate
. Analyze

This not only works for studying but works for other aspects of life as well.
Like for example in gaming.
