= Setup
// :note-caption: 🗒️ Info
:icons: info-circle

xref:index.adoc[birbrain] uses https://docs.antora.org[Antora] to generate my https://asciidoc.org[AsciiDoc] contents.

== Starting from scratch

Follow this https://docs.antora.org/antora/latest/install-and-run-quickstart[guide].

[NOTE]
====
Make sure to commit the git repository otherwise the site won't be generated.
This error will occur:

----
(@antora/content-classifier): Start page specified for site not found: 知識::index.adoc
----
====

== Automated Site Building on xref:github-pages.adoc[Github Pages]

The structure of this notebook is to have a repository for xref:antora.adoc[Antora] and multiple different repositories for the components.

The process is straightforward: push to the repository of components. This action triggers a workflow, which in turn initiates another workflow that will deploy the Antora document to Github Pages.

[ditaa]
....

+-----------+     +-----------+    +-----------+           +-----------+
|           |     |           |    |           |           |           |
| Component |     | Component |    | Component |           | Component |
|     A     |     |     B     |    |     C     |    ...    |     N     |
|           |     |           |    |           |           |           |
+-----+-----+     +-----+-----+    +-----+-----+           +------+----+
      |                 |                |                        |    
      +-----------------+-------+--------+------------------------+      
                                |                                   
                                | Push Request
                                |
                                v                                  
                   +-------------------------+                             
                   |                         |                             
                   |  Call Antora Repository |                             
                   |  Build Workflow Action  |                             
                   |                         |                             
                   +------------+------------+                             
                                |
                                |
                                v
                       +-------------------+
                       |                   |
                       | Deploy to Github  |
                       |       Pages       |
                       |                   |
                       +-------------------+
....

See xref:github-actions.adoc[].


== Changes

I currently use the https://gitlab.com/antora/antora-ui-default[default antora ui] because I have no idea how to create my own user interface from scratch.
I think it is recommended to bundle your own UI instead of modifying it by parts.

*supplementary_ui/partials* changes:

* edit-this-page.hbs
* footer-content.hbs
* header-content.hbs

== Extensions

* https://gitlab.com/antora/antora-lunr-extension[antora/lunr]
* https://github.com/asciidoctor/asciidoctor-kroki[asciidoctor-kroki]
* https://gitlab.com/djencks/asciidoctor-mathjax.js[djencks/asciidoctor-mathjax]

== Wants

This would require a UI rewrite from scratch meaning I have to learn frontend development?!?!?

* Backlinks
* Note previews
