= XML

To generate XMLs, I recommend using https://docs.python.org/3/library/xml.etree.elementtree.html[ElementTree] to https://docs.python.org/3/library/xml.etree.elementtree.html#building-xml-documents[build xml documents] instead of having to mix and match the XML and XSD schemas.

== Schema

The schema can be found within the same parent directory of *Siemens.Engineering.dll* with the name *Schemas*.
Currently, I am playing with ``C:\Program Files\Siemens\Automation\Portal V18\PublicAPI\V18\Schemas``.

I don't know how to read XMLSchemas so I am using https://pypi.org/project/xmlschema/[xmlschema] library.

I dump out the parts of schema instead.

[, python]
----
import xmlschema

schema = xmlschema.XMLSchema(<<XSD FILE PATH HERE>>)

print("Elements:")
for element in schema.elements:
    print(f"- {element} : {schema.elements[element]}")

print("\nTypes:")
for type_name, schema_type in schema.types.items():
    print(f"- {type_name} : {schema_type}")
----

Each schemas in the directory are not dependent of each other.
I think they act as a reference guide rather than a fully built XML schema (what I am thinking of is a generator or a builder).

.Schemas
****
* SW.Common_v3.xsd
* SW.Interface.Snapshot.xsd
* SW.InterfaceSections_v5.xsd
* SW.PlcBlocks.Access_v4.xsd
* SW.PlcBlocks.CompileUnitCommon_v4.xsd
* SW.PlcBlocks.Graph_v5.xsd
* SW.PlcBlocks.InstanceSupervisions_v3.xsd
* SW.PlcBlocks.LADFBD_v4.xsd
* SW.PlcBlocks.SCL_v3.xsd
* SW.PlcBlocks.STL_v4.xsd
* SW.PlcBlocks.TypeSupervisions_v3.xsd
* SW.TechnologicalObjects_AdditionalDataAxis_v1.xsd
* SW.TechnologicalObjects_AdditionalDataKinematics_v1.xsd
* SW.TechnologicalObjects_AdditionalDataMeasuringInput_v1.xsd
* SW.TechnologicalObjects_AdditionalDataOutputCam_v1.xsd
* SW.TechnologicalObjects_Parameters_v1.xsd
* SW.TechnologicalObjects_ProfileDataCam_v1.xsd
****

When converting a decoded XML back to XML, sometimes you get issues such as https://github.com/sissaschool/xmlschema/issues/241[this] and https://github.com/sissaschool/xmlschema/issues/395[this].
To fix this, simply add ``preserve_root=True`` on both decoding and encoding phase.

[, python]
----
obj = schema.decode(xxx, preserve_root=True)
collection = schema.encode(obj, preserve_root=True)
collection
----

This code is based on the https://xmlschema.readthedocs.io/en/latest/usage.html#data-decoding-and-encoding[documentation].

=== SW.InterfaceSections_v5.xsd

Validates the ``Sections`` child element of ``Interface``.

[NOTE]
This schema is useful for creating multi instancedb.

For example:
[, xml]
----
<Interface>
	<Sections>
		<Section Name="Input" />
		<Section Name="Output" />
		<Section Name="InOut" />
		<Section Name="Static">
			<Member Name="Data_Point_Instance" Datatype="&quot;Data_Point&quot;" Accessibility="Public">
				<AttributeList>
					<BooleanAttribute Name="ExternalAccessible" SystemDefined="true">true</BooleanAttribute>
					<BooleanAttribute Name="ExternalVisible" SystemDefined="true">true</BooleanAttribute>
					<BooleanAttribute Name="ExternalWritable" SystemDefined="true">true</BooleanAttribute>
					<BooleanAttribute Name="UserVisible" Informative="true" SystemDefined="true">true</BooleanAttribute>
					<BooleanAttribute Name="UserReadOnly" Informative="true" SystemDefined="true">false</BooleanAttribute>
					<BooleanAttribute Name="UserDeletable" Informative="true" SystemDefined="true">true</BooleanAttribute>
					<BooleanAttribute Name="SetPoint" SystemDefined="true">true</BooleanAttribute>
				</AttributeList>
				<Sections>
					<Section Name="Input">
						<Member Name="Gate 2" Datatype="Bool" />
						<Member Name="Gate 1" Datatype="Bool" />
					</Section>
					<Section Name="Output">
						<Member Name="Open" Datatype="Bool" />
					</Section>
					<Section Name="InOut" />
					<Section Name="Static" />
				</Sections>
			</Member>
		</Section>
		<Section Name="Temp" />
		<Section Name="Constant" />
	</Sections>
</Interface>
----

If the element **Section** contains an attribute, the validation will fail.

== FlgNet

=== Wires

Every network calls (instances) will always have a wire named "en".

[, xml]
----
...
<NameCon UId="21" Name="en" />
...
----

New wires will be created similar to "en" with its specific parameter name from the parts with the UId of the call.

[, xml]
----
...
<NameCon UId="21" Name="Wire 1" />
...

...
<NameCon UId="21" Name="Wire 2" />
...

...
<NameCon UId="21" Name="Wire 3" />
...
----

If a wire is not connected to anything, it will always have "OpenCon" in its element.

[, xml]
----
...
<OpenCon UId="23" />
<NameCon UId="21" Name="en" />
...
----

== Organization Block

In general, UIds for all attributes should be unique to avoid errors.
An example of this error is ``There are at least two definitions for UIds. The incorrect unique ID is '132'.``

.Main Body
[, xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Document>
	<SW.Blocks.OB ID="0">
		<AttributeList>
			<Name>$NAME</Name>
			<Namespace />
			<Number>$NUMBER</Number> <.>
			<ProgrammingLanguage>$PROGRAMMING_LANGUAGE</ProgrammingLanguage>
			<SecondaryType>ProgramCycle</SecondaryType>
		</AttributeList>
		<ObjectList>
			<MultilingualText ID="1" CompositionName="Comment">
				<ObjectList>
					<MultilingualTextItem ID="2" CompositionName="Items">
						<AttributeList>
							<Culture>en-US</Culture>
							<Text />
						</AttributeList>
					</MultilingualTextItem>
				</ObjectList>
			</MultilingualText>
			   <SW.Blocks.CompileUnit />  <.>
			<MultilingualText ID="D" CompositionName="Title">
				<ObjectList>
					<MultilingualTextItem ID="E" CompositionName="Items">
						<AttributeList>
							<Culture>en-US</Culture>
							<Text>"Main Program Sweep (Cycle)"</Text>
						</AttributeList>
					</MultilingualTextItem>
				</ObjectList>
			</MultilingualText>
		</ObjectList>
	</SW.Blocks.OB>
</Document>
----
<.> Acceptable values must be within this range: ``1; 123-32767``.
<.> Refer to this XML attribute: <<compileunit, SW.Blocks.CompileUnit>>.


[#compileunit]
.SW.Blocks.CompileUnit
[, xml]
----
<SW.Blocks.CompileUnit ID="$ID" CompositionName="CompileUnits">
	<AttributeList>
		<NetworkSource>
			<FlgNet
				xmlns="http://www.siemens.com/automation/Openness/SW/NetworkSource/FlgNet/v4">
				<Parts>
					$PARTS
				</Parts>
				<Wires>
					<Wire /> <.>
				</Wires>
			</FlgNet>
		</NetworkSource>
		<ProgrammingLanguage>$PROGRAMMING_LANGUAGE</ProgrammingLanguage>
	</AttributeList>
</SW.Blocks.CompileUnit>
----
<.> Refer to this XML attribute: <<wire_a, Wire (First)>> or <<wire_b, Wire>>.

[#call]
.Call
[, xml]
----
<Call UId="$UID">
	<CallInfo Name="$NAME" BlockType="$BLOCK_TYPE">
		<IntegerAttribute Name="BlockNumber" Informative="true">$BLOCK_NUMBER</IntegerAttribute>
		<Instance Scope="GlobalVariable" UId="$INSTANCE_UID">
			<Component Name="$COMPONENT_NAME" />
			<Address Area="DB" Type="$DB_TYPE" BlockNumber="$DB_BLOCK_NUMBER" BitOffset="0" Informative="true" />
		</Instance>
	</CallInfo>
</Call>
----

[#wire_a]
.Wire (First)
[, xml]
----
<Wire UId="$UID">
	<Powerrail />
	<NameCon UId="$EN_UID" Name="en" /> <.>
</Wire>
----
<.> Must be a value from a ``<<call, Call>>`` UId.

[#wire_b]
.Wire
[, xml]
----
<Wire UId="$UID">
	<NameCon UId="$ENO_UID" Name="eno" />
	<NameCon UId="$EN_UID" Name="en" /> <.>
</Wire>
----
<.> Must be a value from a ``<<call, Call>>`` UId.
