= 日本語

== 曜日

[%header, format=csv]
|===
漢字,英語,ふりがな
日曜日,Sunday,にちようび
月曜日,Monday,げつようび
火曜日,Tuesday,かようび
水曜日,Wednesday,すいようび
木曜日,Thursday,もくようび
金曜日,Friday,きんようび
土曜日,Saturday,どようび
|===

== 数字

[%header, format=csv]
|===
漢字,英語,ふりがな
零,0,れい
一,1,いち
二,2,に
三,3,さん
四,4,し/よん
五,5,ご
六,6,ろく
七,7,なな/しち
八,8,はち
九,9,じゅう
十,10,きゅう
百,100,ひゃく
千,"1,000",せん
万,"10,000",まん
|===

== 挨拶

[%header, format=csv]
|===
漢字,英語,ふりがな
お早う御座います,Good morning (polite),おはようございます
今日は,Hello / Good afternoon,こんにちは
今晩は,Good evening,こんばんは
お休みなさい,Good night,おやすみなさい
さようなら,Good bye,さようなら
でわ、また,See you later,でわ、また
(では) お元気で,Stay healthy / A way of saying good bye,（では）おげんきで
お願いします,Please (do this for me),おねがいします
有難うございます,Thank you (polite),ありがとうございます
どうも有難うございます,Thank you very much,どうもありがとうございます
済みません,Excuse me ,すみません
すみません,I am sorry,すみません
失礼します / 失礼しました,"Literally: “I will commit a rudeness / I committed a rudeness”. It is most often used when asking someone to make space or when you really want to apologize for something.",しつれいします / しつれいしました
いいえ,No / Not at all,いいえ
どう致しましって,It’s my pleasure,どういたしましって
行ってきます,I will go and come back,いってきます
行ってらっしゃい,Please go and come back,いってらっしゃい
只今,I am home,ただいま
お帰りなさい,Welcome home,おかえりなさい
いらっしゃいませ,Welcome (to our shop),いらっしゃいませ
頂きます,Thank you for the meal (before eating),いただきます
ご馳走様でした,Thank you for the meal (after eating),ごちそうさまでした
初めまして,""How do you do?" / First meeting",はじめまして
どうぞ宜しく,Pleased to meet you,どうぞよろしく
こちらこそ,It is I who should say so,こちらこそ
|===
