= 日本語

== 曜日

[%header, format=csv]
|===
漢字,英語,ふりがな
日曜日,Sunday,にちようび
月曜日,Monday,げつようび
火曜日,Tuesday,かようび
水曜日,Wednesday,すいようび
木曜日,Thursday,もくようび
金曜日,Friday,きんようび
土曜日,Saturday,どようび
|===

== 数字

[%header, format=csv]
|===
漢字,英語,ふりがな
零,0,れい
一,1,いち
二,2,に
三,3,さん
四,4,し/よん
五,5,ご
六,6,ろく
七,7,なな/しち
八,8,はち
九,9,じゅう
十,10,きゅう
百,100,ひゃく
千,"1,000",せん
万,"10,000",まん
|===

== 挨拶

[%header, format=csv]
|===
漢字,英語,ふりがな
お早う御座います,Good morning (polite),おはようございます
今日は,Hello / Good afternoon,こんにちは
今晩は,Good evening,こんばんは
お休みなさい,Good night,おやすみなさい
さようなら,Good bye,さようなら
,See you later,
,Stay healthy / A way of saying good bye,
,Please (do this for me),
有難うございます,Thank you (polite),ありがとうございます
,Thank you very much,
済みません,Excuse me ,すみません
すみません,I am sorry,すみません
,"Literally: “I will commit a rudeness / I committed a rudeness”. It is most often used when asking someone to make space or when you really want to apologize for something.",
いいえ,No / Not at all,いいえ
,It’s my pleasure,
,I will go and come back,
,Please go and come back,
只今,I am home,ただいま
お帰りなさい,Welcome home,おかえりなさい
,Welcome (to our shop),
頂きます,Thank you for the meal (before eating),いただきます
ご馳走様でした,Thank you for the meal (after eating),ごちそうさまでした
初めまして,""How do you do?" / First meeting",はじめまして
,Pleased to meet you,
,It is I who should say so,
|===
