= Just a bunch of websites I scavenged


== Cybersecurity

[%header, format=csv]
|===
Accessed,Name,URL,Description
2023-11-10,KNOB Attack,https://knobattack.com[],Key Negotiation of Bluetooth Attack that affects all devices that "speak Bluetooth".
2024-01-07,Bluetooth Forward and Future Secrecy Attacks and Defenses (CVE 2023-24023),https://github.com/francozappa/bluffs[],"Bluetooth BR/EDR devices with Secure Simple Pairing and Secure Connections pairing in Bluetooth Core Specification 4.2 through 5.4 allow certain man-in-the-middle attacks that force a short key length, and might lead to discovery of the encryption key and live injection, aka BLUFFS."
2024-02-11,Nightmare,https://guyinatuxedo.github.io[],Nightmare is an intro to binary exploitation / reverse engineering course based around ctf challenges.
2024-02-11,Reverse Engineering 101,https://malwareunicorn.org/workshops/re101.html[],A workshop that provides the fundamentals of reversing engineering (RE) Windows malware using a hands-on experience with RE tools and techniques.
2024-02-11,pwn.college,https://pwn.college[],"An education platform for students to learn about, and practice, core cybersecurity concepts in a hands-on fashion."
|===

== Projects

[%header, format=csv]
|===
Accessed,Name,URL,Description
2023-07-21,Iced,https://github.com/iced-rs/iced[],"A cross-platform GUI library for Rust, inspired by Elm."
|===

== Hardware

[%header, format=csv]
|===
Accessed,Name,URL,Description
2024-01-04,FCC ID Database,https://fccid.io[],The information resource for all wireless device applications filed with the FCC.
|===

== Document Assistance

[%header, format=csv]
|===
Accessed,Name,URL,Description
2023-04-28,Resume Making,https://www.careercup.com/resume[],"This Is What A GOOD Resume Should Look Like."
2024-02-27,Resume Worded,https://resumeworded.com[],"Improve your resume and LinkedIn profile."
|===

== 東方 Project

[%header, format=csv]
|===
Accessed,Name,URL,Description
2022-10-16,Score & Piano Compilation,http://illusionaryscore.web.fc2.com/score.html[],"A compilation of Piano Scores of the Touhou Series from various artist's are presented here."
2022-11-05,Touhou Lossless Music Collection,http://www.tlmc.eu[],"Almost entire archive of music for Touhou series downloadable through torrent."
2022-11-05,Doujinshi Spotify List,https://www.thspotify.moe[],"Find the Touhou doujin music artists you are looking for easily on Spotify with Touhou Spotify Music!"
2023-11-21,Game Tools and Modification,https://en.touhouwiki.net/wiki/Game_Tools_and_Modifications[],"List of tools and resources for Touhou series."
2024-01-02,Touhou Things,http://151.80.40.155[],"Online player where you can directly play or download music from TLMC. Although the music collection is incomplete."
|===



== Haven't Checked


* Articles
** [A Compression Resistant Steganography Based on Differential Manchester Code](https://www.mdpi.com/2073-8994/13/2/165)
** [AES Proposal: Rijndael](https://csrc.nist.gov/csrc/media/projects/cryptographic-standards-and-guidelines/documents/aes-development/rijndael-ammended.pdf)
* [Cryptohack](https://cryptohack.org/) *A fun, free platform for learning modern cryptography*
* CVEs
** [(CVE-2022-21894) baton drop: Secure Boot Security Feature Bypass Vulnerability](https://github.com/Wack0/CVE-2022-21894)
* [Fawkes](https://sandlab.cs.uchicago.edu/fawkes/) *Image "Cloaking" for Personal Privacy*
* Github
** [Anime Girls Holding Programming Books](https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books "https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books")
** [Lenovo Ideapad Gaming 3 2021 Linux RGB Keyboard Light Controller](https://github.com/InstinctEx/lenovo-ideapad-legion-keyboard-led)
** [Text to Handwriting](https://saurabhdaware.github.io/text-to-handwriting/)
* Resources
** [Anna's Archive](https://annas-archive.org/)
** [Ripped](https://ripped.guide/) *This is a collection of sites and tools that are trusted by the community.*
** [Skull Security Wiki](https://wiki.skullsecurity.org/index.php/Main_Page)
** [Assembly Language / Reversing / Malware Analysis / Game Hacking](https://gist.github.com/muff-in/ff678b1fda17e6188aa0462a99626121)
* Tutorials
** [Coding Interview University](https://github.com/jwasham/coding-interview-university)
** [Guide for GPU Passthrough on laptop with Optimus Manager](https://github.com/mysteryx93/GPU-Passthrough-with-Optimus-Manager-Guide)
** [Project Based Learning](https://github.com/practical-tutorials/project-based-learning)
** [Security Study Plan](https://github.com/jassics/security-study-plan)
** [Summary of 'Clean code'](https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29)
* [XToolBox](https://github.com/xemulat/XToolbox) *A collection of 150+ Windows 10/11 optimization and tweaking apps! *

'''

=== Computer Science

* https://missing.csail.mit.edu/
* https://missing.csail.mit.edu/2020/version-control/
* https://cs.paperswithcode.com/
* http://gameprogrammingpatterns.com/contents.html
* https://github.com/bmorelli25/Become-A-Full-Stack-Web-Developer
* https://github.com/Developer-Y/cs-video-courses
* https://github.com/ossu/computer-science
* https://overapi.com/
* https://dbis-uibk.github.io/relax/calc/local/uibk/local/0
* https://github.com/SkalskiP/courses

=== Pentesting

* https://github.com/carpedm20/awesome-hacking
* https://github.com/husnainfareed/Awesome-Ethical-Hacking-Resources
* https://github.com/nixawk/pentest-wiki
* https://github.com/enaqx/awesome-pentest
* https://github.com/onlurking/awesome-infosec
* https://github.com/hmaverickadams/Beginner-Network-Pentesting
* https://github.com/cider-security-research/cicd-goat
* https://github.com/vavkamil/awesome-vulnerable-apps


=== Awesomes

* [awesome-malware-analysys](https://github.com/rshipp/awesome-malware-analysis#Resources)
