= Just a bunch of websites I scavenged

== Software Engineering
[%header, format=csv]
|===
Accessed,Name,URL,Description
2025-01-15,"Test Driven Development Github",https://github.com/test-driven-development[],"Contains a lot of repositories related to TDD. Some includes books as well."
|===

== Cybersecurity

[%header, format=csv]
|===
Accessed,Name,URL,Description
2023-01-05,OpenSecurityTraining,https://opensecuritytraining.info[],"OpenSecurityTraining2's mission is to provide the world's deepest and best cybersecurity training. That our classes are free is just a bonus!"
2023-11-11,Security Study Plan,https://github.com/jassics/security-study-plan[],"Complete Practical Study Plan to become a successful cybersecurity engineer based on roles like Pentest, AppSec, Cloud Security, DevSecOps and so on..."
2024-02-21,arcX,https://arcx.io[],"Globally accredited cyber security training courses on the arcX platform"
2024-03-19,ISC2 Certified in Cybersecurity Entry-Level Certification,https://www.isc2.org/certifications/cc[],"FREE Cybersecurity Training and Exam! Now for a Limited Time"
2024-03-26,CLARK,https://clark.center[],"CLARK is the largest platform that provides FREE cybersecurity curriculum. It is home to high-value, high-impact cyber curriculum created by top educators and reviewed for relevance and quality."
2024-04-24,CS50’s Introduction to Cybersecurity,https://cs50.harvard.edu/cybersecurity[],"An introduction to cybersecurity for technical and non-technical audiences alike. Learn how to secure your accounts, data, systems, and software against today’s threats and how to recognize and evaluate tomorrow’s as well, both at home and at work. Learn how to preserve your own privacy."
2024-05-18,Cybercademy,https://cybercademy.org/training-platforms[],"A cybersecurity training platform for practical application."
2024-06-06,Blue Team Labs Online,https://blueteamlabs.online[],"Our platform is the perfect place for established cyber defenders to practice in realistic scenarios and showcase their skills in a gamified and competitive environment. Paired with external training or self-study BTLO can develop your technical capability to investigate and defend against cyber attacks and intrusions."
2024-06-06,LetsDefend,https://www.letsdefend.io/[],"LetsDefend helps you build a blue team career with hands-on experience by investigating real cyber attacks inside a simulated SOC."
2024-06-06,CyberDefenders,https://cyberdefenders.org[],"CyberDefenders is a blue team training platform for SOC analysts, threat hunters, security blue teams and DFIR professionals to advance CyberDefense skills."
2025-04-09,APIsecU,https://www.apisecuniversity.com/[],"The API Security University (APIsecU) was founded on the belief that web application programming interfaces (APIs) are a vital pipeline for data to flow across the Internet. We realized that APIs are a leading attack vector for criminals and are continuously being adopted by organizations without sufficient security controls in place. At scale, this situation creates a perfect storm for criminals to breach data, devastate businesses, and expose sensitive information worldwide."
2025-04-30,CyberTalents,https://cybertalents.com/[],"Cyber Talents is a platform that ranks cyber security talents according to their real hands on skills in different cyber security categories by running capture the flag competitions in order to be hired by recruiters."
|===


== Open Source Intelligence

[%header, format=csv]
|===
Accessed,Name,URL,Description
2025-04-30,TweetedAt,https://oduwsdl.github.io/tweetedat/[],"Find the date and time of a tweet."
|===


== Privacy


[%header, format=csv]
|===
Accessed,Name,URL,Description
2022-03-05,Fawkes,https://sandlab.cs.uchicago.edu/fawkes[],"Image "Cloaking" for Personal Privacy"
|===



== Writeups / Discoveries / CVEs / Resources

[%header, format=csv]
|===
Accessed,Name,URL,Description
2023-01-15,baton drop: Secure Boot Security Feature Bypass Vulnerability (CVE-2022-21894),https://github.com/Wack0/CVE-2022-21894[],"Windows Boot Applications allow the truncatememory setting to remove blocks of memory containing "persistent" ranges of serialised data from the memory map, leading to Secure Boot bypass."
2023-05-24,Skull Security Wiki,https://wiki.skullsecurity.org[],"Someone's wiki about what they found."
2023-07-28,A Compression Resistant Steganography Based on Differential Manchester Code,https://www.mdpi.com/2073-8994/13/2/165[],"Steganography research about resisting image compression from Facebook, Twitter, and WeChat."
2023-07-30,Zenbleed (CVE-2023-20593),https://lock.cmpxchg8b.com/zenbleed.html[],"The Zenbleed exploit significantly impacts the security of systems running AMD's Zen 2 processors, including popular CPUs like the Ryzen 5 3600 and the entire Zen 2 product stack."]
2023-07-30,StackRot (CVE-2023-3269),https://github.com/lrh2000/StackRot[],"Linux kernel privilege escalation vulnerability"
2023-09-16,Google's Security Research,https://github.com/google/security-research[],"This project hosts security advisories and their accompanying proof-of-concepts related to research conducted at Google which impact non-Google owned code."
2023-11-10,KNOB Attack,https://knobattack.com[],Key Negotiation of Bluetooth Attack that affects all devices that "speak Bluetooth".
2024-01-07,Bluetooth Forward and Future Secrecy Attacks and Defenses (CVE 2023-24023),https://github.com/francozappa/bluffs[],"Bluetooth BR/EDR devices with Secure Simple Pairing and Secure Connections pairing in Bluetooth Core Specification 4.2 through 5.4 allow certain man-in-the-middle attacks that force a short key length, and might lead to discovery of the encryption key and live injection, aka BLUFFS."
2024-02-09,SSH ProxyCommand == unexpected code execution (CVE-2023-51385),https://vin01.github.io/piptagole/ssh/security/openssh/libssh/remote-code-execution/2023/12/20/openssh-proxycommand-libssh-rce.html[],"SSH’s ProxyCommand is a feature quite widely used to proxy ssh connections by allowing to specify custom commands to be used to connect to the server. Arguments to this directive may contain tokens like %h, %u which refer to hostname and username respectively."
|===


== Malware Development
[%header, format=csv]
|===
Accessed,Name,URL,Description
2024-02-21,Shellcodes database for study cases,https://shell-storm.org/shellcode/index.html[],"List of shell codes"
|===

== Ransomware

[%header, format=csv]
|===
Accessed,Name,URL,Description
2024-11-06,ID Ransomware,https://id-ransomware.malwarehunterteam.com/[],"Upload a ransom note and/or sample encrypted file to identify the ransomware that has encrypted your data."
|===

== xref:ROOT:reverse-engineering.adoc[Reverse Engineering]

[%header, format=csv]
|===
Accessed,Name,URL,Description

2023-10-29,"Rust Binary Analysis, Feature By Feature",https://research.checkpoint.com/2023/rust-binary-analysis-feature-by-feature[],"Writeup comparison between C/C++ binary analysis with Rust."
2024-02-11,Modern Binary Exploitation — CSCI 4968,https://github.com/RPISEC/MBE[],"This repository contains the materials as developed and used by RPISEC to teach Modern Binary Exploitation at Rensselaer Polytechnic Institute in Spring 2015. This was a university course developed and run solely by students to teach skills in vulnerability research, reverse engineering, and binary exploitation."
2024-02-11,Nightmare,https://guyinatuxedo.github.io[],Nightmare is an intro to binary exploitation / reverse engineering course based around ctf challenges.
2024-02-11,Reverse Engineering 101,https://malwareunicorn.org/workshops/re101.html[],A workshop that provides the fundamentals of reversing engineering (RE) Windows malware using a hands-on experience with RE tools and techniques.
2024-02-11,Simple x86_64 buffer overflow in gdb,https://oxasploits.com/posts/simple-buffer-overflow-exploitation-walkthrough-gdb[],"Debugging a C buffer overflow in gdb to attain higher privileges."
2024-02-11,Practical Binary Analysis,https://practicalbinaryanalysis.com[],"Practical Binary Analysis covers all major binary analysis topics in an accessible way, from binary formats, disassembly, and basic analysis to advanced techniques like binary instrumentation, taint analysis, and symbolic execution."
2024-01-19,Awesome Malware Analysis,https://github.com/rshipp/awesome-malware-analysis[],"A curated list of awesome malware analysis tools and resources."
2024-09-12,Microcorruption,https://microcorruption.com[],"tl;dr: Given a debugger and a device, find an input that unlocks it. Solve the level with that input. You've been given access to a device that controls a lock. Your job: defeat the lock by exploiting bugs in the device's code."
2024-11-07,MAS Crackmes,https://mas.owasp.org/crackmes/[],"Welcome to the MAS Crackmes aka. UnCrackable Apps, a collection of mobile reverse engineering challenges. These challenges are used as examples throughout the OWASP MASTG. Of course, you can also solve them for fun."
|===


== Cryptography


[%header, format=csv]
|===
Accessed,Name,URL,Description
2021-09-11,AES Proposal: Rijndael,https://csrc.nist.gov/csrc/media/projects/cryptographic-standards-and-guidelines/documents/aes-development/rijndael-ammended.pdf[],"Something along the lines of cryptography."
2023-06-05,the cryptopals crypto challenges,https://www.cryptopals.com[],"A collection of exercises that demonstrate attacks on real-world crypto."
2024-02-11,Cryptohack,https://cryptohack.org[],"A fun, free platform for learning modern cryptography"
2025-04-09,MysteryTwister,https://mysterytwister.org[],"MysteryTwister is a cipher contest, where you can solve cryptographic riddles (challenges) of different difficulty levels. If you are successful, you will be immortalized in the Hall of Fame."
2025-04-09,The Joy of Cryptography,https://joyofcryptography.com/[],"The Joy of Cryptography is a free undergraduate-level textbook that introduces students to the fundamentals of provable security."
2025-04-09, A Graduate Course in Applied Cryptography,https://toc.cryptobook.us/[],"The book covers many constructions for different tasks in cryptography. For each task we define a precise security goal that we aim to achieve and then present constructions that achieve the required goal."
|===


== Web Security

[%header, format=csv]
|===
Accessed,Name,URL,Description
2024-06-21,PortSwigger Web Security Academy,https://portswigger.net/web-security[],"Free, online web security training from the creators of Burp Suite."
2024-04-28,bWAPP Files,https://sourceforge.net/projects/bwapp/files/bee-box[],"bWAPP, or a buggy web application, is a free and open source deliberately insecure web application."
|===

== Packet Sniffing
[%header, format=csv]
|===
Accessed,Name,URL,Description
2024-01-9,QCSuper,https://github.com/P1sec/QCSuper[]," QCSuper is a tool communicating with Qualcomm-based phones and modems, allowing to capture raw 2G/3G/4G radio frames, among other things. "
|===



== Capture The Flags / Wargames

[%header, format=csv]
|===
Accessed,Name,URL,Description
2021-03-11,OverTheWire,https://overthewire.org/wargames[],"The wargames offered by the OverTheWire community can help you to learn and practice security concepts in the form of fun-filled games."
2022-03-21,pwnable.kr,http://pwnable.kr[],"A wargame for reverse engineering."
2022-03-21,reversing.kr,http://reversing.kr[],"A wargame for reverse engineering."
2023-11-21,Root-Me.org,https://www.root-me.org[],"The fast, easy, and affordable way to train your hacking skills."
2024-02-11,pwn.college,https://pwn.college[],"An education platform for students to learn about, and practice, core cybersecurity concepts in a hands-on fashion."
2024-02-11,W3Challs,https://w3challs.com[],"Offers security challenges to learn and practice hacking."
2024-03-24,HackMyVM,https://hackmyvm.eu[],"VMs made by the users for the users"
2024-06-06,Vulnmachines,https://vulnmachines.com[],"Vulnmachines is a cybersecurity learning platform where security enthusiasts can get a hands-on experience of various skills in different cybersecurity categories through Capture The Flag Contests."
|===

== Computer Networking

[%header, format=csv]
|===
Accessed,Name,URL,Description
2023-11-05,Customizing ICMP Payload in Ping Command,https://gursimarsm.medium.com/customizing-icmp-payload-in-ping-command-7c4486f4a1be[],"Something related to ICMP echo requests."
|===


== Rust

[%header, format=csv]
|===
Accessed,Name,URL,Description
2023-07-21,Iced,https://github.com/iced-rs/iced[],"A cross-platform GUI library for Rust, inspired by Elm."
2024-04-05,rustaceanvim,https://github.com/mrcjkb/rustaceanvim[],"Supercharge your Rust experience in Neovim! A heavily modified fork of rust-tools.nvim"
|===

== C

[%header, format=csv]
|===
Accessed,Name,URL,Description
2024-04-04,The Underhanded C Contest,http://www.underhanded-c.org/_m_200910.html[],"An annual contest to write innocent-looking C code implementing malicious behavior. In this contest you must write C code that is as readable, clear, innocent and straightforward as possible, and yet it must fail to perform at its apparent function. To be more specific, it should perform some specific underhanded task that will not be detected by examining the source code."
|===



== Hardware

[%header, format=csv]
|===
Accessed,Name,URL,Description
2022-09-11,Lenovo RGB Keyboard Light Controller,https://github.com/InstinctEx/lenovo-ideapad-legion-keyboard-led[],"LED backlight keyboard controller written in python for your Lenovo Ideapad Gaming 3/Legion 5 Pro 2021 laptop."
2024-01-04,FCC ID Database,https://fccid.io[],The information resource for all wireless device applications filed with the FCC.
|===

== Virtualization


[%header, format=csv]
|===
Accessed,Name,URL,Description
2022-08-24,Guide for GPU Passthrough on laptop with Optimus Manager,https://github.com/mysteryx93/GPU-Passthrough-with-Optimus-Manager-Guide[],"Guide for VFIO GPU Passthrough on laptop with Optimus Manager"
|===

== Document Assistance

[%header, format=csv]
|===
Accessed,Name,URL,Description
2022-12-01,Text to Handwriting,https://github.com/saurabhdaware/text-to-handwriting[],"So your teacher asked you to upload written assignments? Hate writing assigments? This tool will help you convert your text to handwriting xD "
2023-04-28,Resume Making,https://www.careercup.com/resume[],"This Is What A GOOD Resume Should Look Like."
2024-01-03,Academic Phrasebank – The Largest Collection of Academic Phrases,https://www.ref-n-write.com[],"Helps you write academic papers such as short phrases or context."
2024-02-27,Resume Worded,https://resumeworded.com[],"Improve your resume and LinkedIn profile."
|===

== 日本語

[%header, format=csv]
|===
Accessed,Name,URL,Description
2024-03-02,さくら多読ラボ,https://jgrpg-sakura.com[],"You can read easy Japanese books here. Japanese Graded Reader SAKURA is a library with a range of books from beginner to upper intermediate. Please enjoy reading without using a dictionary. Please read as much as possible."
|===

== 東方 Project

[%header, format=csv]
|===
Accessed,Name,URL,Description
2022-10-16,Score & Piano Compilation,http://illusionaryscore.web.fc2.com/score.html[],"A compilation of Piano Scores of the Touhou Series from various artist's are presented here."
2022-11-05,Touhou Lossless Music Collection,http://www.tlmc.eu[],"Almost entire archive of music for Touhou series downloadable through torrent."
2022-11-05,Doujinshi Spotify List,https://www.thspotify.moe[],"Find the Touhou doujin music artists you are looking for easily on Spotify with Touhou Spotify Music!"
2023-11-21,Game Tools and Modification,https://en.touhouwiki.net/wiki/Game_Tools_and_Modifications[],"List of tools and resources for Touhou series."
2024-01-02,Touhou Things,http://151.80.40.155[],"Online player where you can directly play or download music from TLMC. Although the music collection is incomplete."
2024-03-25,Map,https://map.thwiki.cc[],"A Touhou map."
|===

== Anime


[%header, format=csv]
|===
Accessed,Name,URL,Description
2023-04-11,Anime Girls Holding Programming Books,https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books[],"Images of anime girls holding programming books. Literally."
2023-06-06,AniWave,https://aniwave.to[],"Watch HD anime online."
|===


== Material Collections


[%header, format=csv]
|===
Accessed,Name,URL,Description
2022-05-18,Ripped,https://ripped.guide[],"This is a collection of sites and tools that are trusted by the community."
2023-11-02,Open Source Cybersecurity Projects,https://nicoleenesse.notion.site/Open-Source-Cybersecurity-Projects-04419423bb6d43b8a93c8d9b9c19d5d4[],"Top cybersecurity projects to create."
2023-12-18,Project Based Learning,https://github.com/practical-tutorials/project-based-learning[],"Curated list of project-based tutorials"
2024-01-02,Anna's Archive,https://annas-archive.org[],"📚 The largest truly open library in human history. ⭐️ We mirror Sci-Hub and LibGen. We scrape and open-source Z-Lib, Internet Archive Lending Library, DuXiu, and more."
2024-02-11,Assembly Language / Reversing / Malware Analysis / Game Hacking,https://gist.github.com/muff-in/ff678b1fda17e6188aa0462a99626121[],"Lots of links pointing to various resources."
|===


== Obsidian

[%header, format=csv]
|===
Accessed,Name,URL,Description
2024-02-02,Templater snippets,https://zachyoung.dev/posts/templater-snippets[],"Snippets zachyoung written written for the https://github.com/SilentVoid13/Templater[Templater] Obsidian plugin."
|===


== Windows


[%header, format=csv]
|===
Accessed,Name,URL,Description
2020-11-04,Adguard,https://files.rg-adguard.net[],"List of files by Microsoft®"
2023-02-21,XToolBox,https://github.com/xemulat/XToolbox[],"A collection of 150+ Windows 10/11 optimization and tweaking apps!"
|===




== Haven't Checked


* Tutorials
** [Coding Interview University](https://github.com/jwasham/coding-interview-university)
** [Summary of 'Clean code'](https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29)
* https://www.reddit.com/r/linux4noobs/comments/18pfvsb/comment/kep1mwp/?context=3
* https://gist.github.com/lewixlabs/e6b59b742ecb072f5747a908e14f412c
* https://lifeinhex.com/updated-meltdown-and-enigmavb-unpacker/


'''

=== Computer Science

* https://sp24.cs161.org/
* https://missing.csail.mit.edu/
* https://missing.csail.mit.edu/2020/version-control/
* https://cs.paperswithcode.com/
* http://gameprogrammingpatterns.com/contents.html
* https://github.com/bmorelli25/Become-A-Full-Stack-Web-Developer
* https://github.com/Developer-Y/cs-video-courses
* https://github.com/ossu/computer-science
* https://overapi.com/
* https://dbis-uibk.github.io/relax/calc/local/uibk/local/0
* https://github.com/SkalskiP/courses

=== Pentesting

* https://github.com/carpedm20/awesome-hacking
* https://github.com/husnainfareed/Awesome-Ethical-Hacking-Resources
* https://github.com/nixawk/pentest-wiki
* https://github.com/enaqx/awesome-pentest
* https://github.com/onlurking/awesome-infosec
* https://github.com/hmaverickadams/Beginner-Network-Pentesting
* https://github.com/cider-security-research/cicd-goat
* https://github.com/vavkamil/awesome-vulnerable-apps
* https://github.com/PanXProject/awesome-certificates



== Someone's notes

. https://hackmd.io/@Kiyent/SkDtF2_2T[AI Links]
