= random

== xref:avviki.adoc[avviki]

making my own antora vim wiki plugin thingy

== job salary expectations when listed in job posting

when asked these questions:

[qanda]
What are your salary expectations for this role?::
Mention the salary range in the job description.
Ask if it's still the case.

Yes, does that align with your expectations?::
Mention what you want.
If you want a higher salary, mention that a higher end aligns with your expectations.

We'd love to offer you a job. Do you accept?::
Don't answer on the spot.
Don't ask for the pay.
Don't negotiate.
First thank them for the job offer, second be grateful to join the team, third ask them for the offer letter in email so that you can review the specifications.

Last thing to do is to be grateful again.
Then push for higher end of the salary if it's not enough.


== life lessons maybe?

[NOTE]
.*Here’s 32 things I’ve learned that I hope help you in your journey*:
====

. Nothing worthwhile comes easy. 
. Work on a passion project, even just 30 minutes a day. It compounds.
. Become a lifelong learner (best tip).
. Working from 7am to 7pm isn’t productivity. It’s guilt.
. To be really successful become useful.
. Like houses in need of repair, problems usually don’t fix themselves.
. Don’t say something to yourself that you wouldn’t say to someone else. 
. Try to spend 12 minutes a day in quiet reflection, meditation, or prayer.
. Try new things. If it doesn’t work out, stop. At least you tried.
. You can’t control everything. Focus on what you can control.
. If you think you have it tough, look around.
. It's only over when you say it is.
. ...
====

Source: link:https://www.reddit.com/r/lifehacks/comments/1bgw44k/i_turned_72_today/[Reddit]


